gymManagementSys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('', views.home, name="home"),
    path('pagedetail/<int:id>/', views.page_detail, name="pagedetail"),
    path('faq/', views.faq_list, name="faq"),
    path('enquiry/', views.enquiry, name="enquiry"),
    path('gallery/', views.gallery, name="gallery"),
    path('gallerydetail/<int:id>/', views.gallery_detail, name="gallerydetail"),
    path('pricing/', views.pricing, name="pricing"),
    path('accounts/signup/', views.signup, name="signup"),
    path('checkout/<int:plan_id>/', views.checkout, name="checkout"),
    path('user-dashboard/', views.user_dashboard, name="user_dashboard"),
    #user-dashboard section part
    path('update-profile/', views.update_profile, name="update_profile"),
    #trainer login-logout
    path('trainerlogin/', views.trainerlogin, name="trainerlogin"),
    path('trainerlogout/', views.trainerlogout, name="trainerlogout"),
    #notification
    path('notifs/', views.notifs, name="notifs"),
    path('get_notifs/', views.get_notifs, name="get_notifs"),



]

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img=models.ImageField(upload_to="services/")

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe(f'<img src="{self.img.url}" width="80"')
   


class Banners(models.Model):
    img=models.ImageField(upload_to="banners/")
    alt_text=models.CharField(max_length=150)

    def __str__(self):
        return self.alt_text

    def image_tag(self):
        return mark_safe(f'<img src="{self.img.url}" width="80"')


class Pages(models.Model):
    title = models.CharField(max_length=200)
    detail = models.TextField()

    def __str__(self):
        return self.title


class Faq(models.Model):
    quest = models.CharField(max_length=200)
    ans = models.TextField()

    def __str__(self):
        return self.quest


class Enquiry(models.Model):
    full_name=models.CharField(max_length=100)
    email = models.EmailField()
    detail = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Gallery(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img=models.ImageField(upload_to="gallery/")

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe(f'<img src="{self.img.url}" width="80"')

class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    alt_text = models.CharField(max_length=150)
    img=models.ImageField(upload_to="gallery_imgs/")

    def __str__(self):
        return self.alt_text

    def image_tag(self):
        return mark_safe(f'<img src="{self.img.url}" width="80"')


class SubPlan(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    max_member = models.IntegerField(null=True)
    highlight_status=models.BooleanField(default=False, null=True)
    validity_days=models.IntegerField(null=True)

    def __str__(self):
        return self.title


class SubPlanFeature(models.Model):
    subplan = models.ManyToManyField(SubPlan)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class PlanDiscount(models.Model):
    subPlan = models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
    total_months = models.IntegerField()
    total_discount = models.IntegerField()

    def __str__(self):
        return str(self.total_months)



class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=150)
    address = models.TextField()
    img=models.ImageField(upload_to="subs/")

    def __str__(self):
        return str(self.user)

    def image_tag(self):
        if self.img:
            return mark_safe(f'<img src="{self.img.url}" width="80"')
        else:
            return 'no-image'


@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwargs):
    if created:
        Subscriber.objects.create(user=instance)

class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(SubPlan, on_delete=models.CASCADE)
    price = models.CharField(max_length=150)
    reg_date = models.DateField(auto_now_add=True, null=True)



class Trainer(models.Model):
    full_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100,null=True)
    pwd = models.CharField(max_length=100,null=True)
    mobile = models.CharField(max_length=100)
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    detail = models.TextField()
    img=models.ImageField(upload_to="trainers/")
    facebook = models.CharField(max_length=100,null=True)
    twitter = models.CharField(max_length=100,null=True)
    youtube = models.CharField(max_length=100,null=True)
    salary = models.IntegerField(default=0)

    def __str__(self):
        return self.full_name

    def image_tag(self):
        if self.img:
            return mark_safe(f'<img src="{self.img.url}" width="80"')
        else:
            return 'no-image'


class Notify(models.Model):
    notify_detail = models.CharField(max_length=100)
    read_by_user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    read_by_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)


    def __str__(self):
        return self.notify_detail



class AssignSubscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)



class TrainerSalary(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    amt=models.IntegerField()
    amt_date=models.DateField()
    remarks=models.TextField(blank=True)

    class Meta:
        verbose_name_plural='Trainer Salary'

    def __str__(self):
        return str(self.trainer.full_name)
  

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Enquiry,Trainer
from django.contrib.auth.models import User
class EnquiryForm(forms.ModelForm):
    class Meta:
        model = Enquiry
        fields = ['full_name','email','detail']


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email','username','password1','password2')

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email','username')


class TrainerForm(forms.ModelForm):
    pwd = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Trainer
        fields = ('username','pwd')

main/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.core import serializers
from django.http import JsonResponse
from django.db.models import Count
from datetime import timedelta

def home(request):
    banners = Banners.objects.all()
    services = Service.objects.all()[:3]
    gimgs = GalleryImage.objects.all().order_by('-id')[:9]
    return render(request, "main/home.html",{"banners":banners,"services":services,"gimgs":gimgs})

def page_detail(request,id):
    page = Pages.objects.get(id=id)
    return render(request,"main/page.html",{"page":page})

def faq_list(request):
    faqs = Faq.objects.all()
    return render(request,"main/faq.html",{"faqs":faqs})

def enquiry(request):
    msg = ""
    form = EnquiryForm()
    if request.method=="POST":
        form = EnquiryForm(request.POST)
        if form.is_valid():
            form.save()
            msg = "Data has been saved successfully"
    return render(request,"main/enquiry.html",{"form":form,"msg":msg})


def gallery(request):
    gallery = Gallery.objects.all().order_by('-id')
    return render(request,"main/gallery.html",{"gallerys":gallery})

def gallery_detail(request,id):
    gallery = Gallery.objects.get(id=id)
    gallery_imgs=GalleryImage.objects.filter(gallery=gallery).order_by('-id')
    return render(request,"main/gallery_imgs.html",{"gallery_imgs":gallery_imgs,"gallery":gallery})

def pricing(request):
    pricing = SubPlan.objects.annotate(total_members=Count('subscription__id')).all().order_by('price')
    dfeatures = SubPlanFeature.objects.all()
    return render(request,"main/pricing.html",{"plans":pricing,"dfeatures":dfeatures})


def signup(request):
    msg=""
    form = SignupForm()
    if request.method=="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            msg="Thanks for registration"
    return render(request,"registration/signup.html",{"form":form,"msg":msg})



def checkout(request,plan_id):
    planDetail = SubPlan.objects.get(pk=plan_id)
    return render(request,"main/checkout.html",{"plan":planDetail})

def user_dashboard(request):
    current_plan = Subscription.objects.get(user=request.user)
    my_trainer = AssignSubscriber.objects.get(user=request.user)
    enddate = current_plan.reg_date+timedelta(days=current_plan.plan.validity_days)
    return render(request,"user/dashboard.html",{"current_plan":current_plan,"my_trainer":my_trainer,"enddate":enddate})

def update_profile(request):
    msg = ""
    if request.method == "POST":
        form = ProfileForm(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            msg = "Profile has been updated"
    form = ProfileForm(instance=request.user)
    return render(request,"user/update_profile.html",{"form":form,"msg":msg})



def trainerlogin(request):
    msg = ""
    form = TrainerForm()
    if request.method=="POST":
        username = request.POST['username']
        pwd = request.POST['pwd']
        trainer = Trainer.objects.filter(username=username, pwd=pwd).count()
        if trainer > 0:
            request.session['trainerLogin']=True
            return redirect('/trainer_dashboard')
        else:
            msg='Invalid Credentials!!'
        
    return render(request,"trainer/login.html",{"form":form,"msg":msg})


def trainerlogout(request):
    del request.session['trainerLogin']
    return redirect('/trainerlogin')


def notifs(request):
    data = Notify.objects.all().order_by('-id')
    return render(request,"notifs.html",{"data":data})

def get_notifs(request):
    data = Notify.objects.all().order_by('-id')
    jsondata = serializers.serialize("json",data)
    return JsonResponse({"data":jsondata})

        

        

templates/main/checkout.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
				<table class="table table-bordered">
					<thead class="table-warning">
						<tr>
							<th>Plan</th>
							<th>Plan Detail</th>
							<th>Payment For</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<table class="table-bordered table">
									<tr>
										<th>Name</th>
										<td>{{plan.title}}</td>
									</tr>
									<tr>
										<th>Price</th>
										<td>${{plan.price}}</td>
									</tr>
									<tr>
										<th>Max Member</th>
										<td>30</td>
									</tr>
									<tr>
										<th>Already Registered</th>
										<td>15</td>
									</tr>
									<tr>
										<th>Balance Seats</th>
										<td>15</td>
									</tr>
								</table>
							</td>
							<td>
								<ul class="list-unstyled">
				              	{% for feature in plan.subplanfeature_set.all %}
						            <li>{{feature.title}}</li>
				            	{% endfor %}
					            </ul>
							</td>
							<td>
								<table class="table table-bordered">
									{% for discount in plan.plandiscount_set.all %}
							            <tr>
											<td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity{{discount.id}}" name="validity" class="select-validity" value="{{discount.total_months}}" /></td>
											<th><label for="validity{{discount.id}}">{{discount.total_months}} Month</label></th>
											<td>{{discount.total_discount}}%</td>
										</tr>
					            	{% endfor %}
								</table>
							</td>
						</tr>
					</tbody>
					<tfoot class="table-info">
						<tr>
							<td></td>
							<th>Total Amount</th>
							<td><b>$<span class="totalAmount">{{plan.price}}</span></b></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td>
								<!-- <form method="post" action="#">
									{% csrf_token %}
									<input type="submit" value="Proceed to Payment" class="btn btn-primary" />
								</form> -->
							</td>
						</tr>
					</tfoot>
				</table>
		</section>
		<!-- End -->
    </main>


<script type="text/javascript">
	$(document).ready(function(){
		$(".select-validity").on('click',function(){
			var _planPrice=$(this).attr('data-planprice');
			var _planValid=$(this).val();
			var _planDisc=$(this).attr('data-discount');
			var _totalPrice=_planPrice*_planValid;
			if(_planDisc>0){
				var _calDisc=_totalPrice*_planDisc/100;
				_calDisc=_totalPrice-_calDisc;
			}else{
				_calDisc=_planPrice;
			}
			$(".totalAmount").text(_calDisc);
		});
	});
</script>

{% endblock %}

templates/main/enquiry.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'imgs/enquiry.jpg' %}" class="img-fluid" /> 
				</div>
				<div class="col-md-6">
					{% if msg %}
					<p class="text-success">{{msg}}</p>
					{% endif %}
					<form method="post" action="{% url 'enquiry' %}">
						{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/main/faq.html
{% extends 'base/base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- FAQ starts -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
			<div class="accordion" id="accordionExample">
				{% for faq in faqs %}
				  <div class="accordion-item">
				    <h2 class="accordion-header" id="headingOne">
				      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
				        {{faq.quest}}
				      </button>
				    </h2>
				    <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
				      <div class="accordion-body">
				        {{faq.ans}}
				      </div>
				    </div>
				  </div>
				  {% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/main/gallery.html
{% extends 'base/base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
			<div class="row">
				{% for gallery in gallerys %}
				<div class="col-md-4 mb-4">
					<div class="card">
					  <img src="{{gallery.img.url}}" class="card-img-top" alt="{{gallery.title}}">
					  <div class="card-body">
					    <h5 class="card-title">{{gallery.title}}</h5>
					    <p class="card-text">{{gallery.detail}}</p>
					    <a href="{% url 'gallerydetail' gallery.id %}" class="btn btn-primary">View All</a>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

templates/main/gallery_imgs.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gallery.title}} Images</h1>
			<div class="row">
				{% for gimg in gallery_imgs %}
				<div class="col-md-4 mb-4">
					<div class="card">
						<a href="{{gimg.img.url}}" data-lightbox="gallery"> <img src="{{gimg.img.url}}" class="card-img-top" alt="{{gimg.alt_text}}"></a>

					  <!-- <a href="{{gimg.img.url}}" data-lightbox="gallery"><img src="{{gimg.img.url}}" width="155" class="img-thumbnail" alt="{{gimg.alt_text}}"></a> -->
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
	<!-- LightBox css -->
<link rel="stylesheet" type="text/css" href="{% static 'lightbox2-dev/dist/css/lightbox.min.css' %}" />
<!-- LightBox Js -->
<script type="text/javascript" src="{% static 'lightbox2-dev/dist/js/lightbox.min.js' %}"></script>
{% endblock %}

templates/main/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!-- Main Start -->
    <main>
    	<!-- banner Start -->
    	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
		  <div class="carousel-inner">
		  	{% for banner in banners %}
		    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
		      <img src="{{banner.img.url}}" class="d-block w-100" alt="Slide 1"></a>
		    </div>
		    {% endfor %}
		  </div>
		  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Previous</span>
		  </button>
		  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Next</span>
		  </button>
		</div>
		<!-- End Banner -->
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading">Services</h1>
			<div class="row">
				{% for service in services %}
				<div class="col-md-4">
					<div class="card">
					  <img src="{{service.img.url}}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h3 class="card-title">{{service.title}}</h3>
					    <p class="card-text">{{service.detail}}</p>
					    <a href="#" class="btn btn-primary">Read More</a>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->

		<!-- Testimonials -->
		<section class="container-fluid bg-light py-4 mt-5 border-top border-bottom">
			<div class="container">
				<div class="row">
					<div class="col-md-5">
							<h1 class="mb-4 section-heading">About Us</h1>
							<p class="lh-base">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1550s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
							<p><a href="{% url 'pagedetail' id=3 %}" class="btn btn-info text-white">Read More</a></p>
					</div>
					<div class="col-md-6 offset-1">
							<h1 class="mb-4 section-heading">Gallery <a href="#" class="float-end btn btn-info text-white mt-2">View All</a></h1>
							<div class="gallery">
								{% for gimg in gimgs %}
								<a href="{{gimg.img.url}}" data-lightbox="gallery"><img src="{{gimg.img.url}}" width="155" class="img-thumbnail" alt="{{gimg.alt_text}}"></a>
								{% endfor %}
							</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Testimonials -->

    </main>
    <!-- End -->

<!-- LightBox css -->
<link rel="stylesheet" type="text/css" href="{% static 'lightbox2-dev/dist/css/lightbox.min.css' %}" />
<!-- LightBox Js -->
<script type="text/javascript" src="{% static 'lightbox2-dev/dist/js/lightbox.min.js' %}"></script>

{% endblock %}

templates/main/page.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!-- Main Start -->
    <main>
    	
		<!-- Page -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading">{{page.title}}</h1>
            <p class="lh-base">{{page.detail}}</p>
			
		</section>
		<!-- End -->

		
    </main>
    <!-- End -->

<!-- LightBox css -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'lightbox2-2.11.3/dist/css/lightbox.min.css' %}" /> -->
<!-- LightBox Js -->
<!-- <script type="text/javascript" src="{% static 'lightbox2-2.11.3/dist/js/lightbox.min.js' %}"></script> -->

{% endblock %}

templates/main/pricing.html
{% extends 'base/base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" /> -->
<section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
<main>
  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
        {% if plan.highlight_status %}
        <div class="card-header py-3 text-white bg-primary border-primary">
          {% else %}
        <div class="card-header py-3">
          {% endif %}
          <h4 class="my-0 fw-normal">{{plan.title}}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">${{plan.price}}
            <small class="text-muted fw-light">/{{plan.validity_days}} Days</small>
          </h1>
    <b><p class="text-success">Member capacity {{plan.max_member|sub:plan.total_members}}</p></b>
          <ul class="list-unstyled mt-3 mb-4">
            {% for feature in plan.subplanfeature_set.all %}
            <li>{{feature.title}}</li>
            {% endfor %}
          </ul>
          {% if request.user.is_authenticated  %}
          <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% else %}
          <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% endif %}

          

        
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <h2 class="display-6 text-center mb-4">Compare plans</h2>
  <div class="table-responsive">
    <table class="table text-center">
      <thead>
        <tr>
          <th style="width: 34%;"></th>
          {% for plan in plans %}
          <th style="width: 22%;">{{plan.title}}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for feature in dfeatures %}
        <tr>
          <th scope="row" class="text-start">{{feature.title}}</th>
          {% for plan in plans %}
          <td>
            {% if plan in feature.subplan.all %}
            ✅  <!--- tick sign --->
            {% else %}
            ❌ <!--- cross sign --->
            {% endif %}
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
</section>
{% endblock %}